# =============== Window =================
# Transparency
background_opacity 0.6

# Padding (kitty has separate options for top/bottom/left/right)
window_padding_width 6 6 6 6
confirm_os_window_close 0

# =============== Shell ==================
# Launch xonsh instead of default shell
shell xonsh

# =============== Selection ==============
# Copy on select
copy_on_select yes
# Automatically paste to clipboard
clipboard_control write-clipboard write-primary

# =============== Fonts ==================
font_family      JetBrainsMono Nerd Font Propo
bold_font        JetBrainsMono Nerd Font Propo Bold
italic_font      JetBrainsMono Nerd Font Propo Italic
bold_italic_font JetBrainsMono Nerd Font Propo Bold Italic
font_size        11.5
font_hinting slight
text_antialiasing slight
force_lcdfilter lcdlight
gamma 0.9
draw_bold_text_with_bright_colors = true
text_alpha 1.0
adjust_line_height 120%

# Make text edges crisper
font_hinting full
text_antialiasing full
force_lcdfilter lcddefault

# Reduce squish (adjust spacing)
adjust_column_width 102%



# =============== Colors =================
foreground #a9b1d6
background #000000

color0  #000000
color1  #d54e53
color2  #b9ca4a
color3  #e6c547
color4  #7aa6da
color5  #c397d8
color6  #70c0ba
color7  #eaeaea

color8  #666666
color9  #ff3334
color10 #9ec400
color11 #e7c547
color12 #7aa6da
color13 #b77ee0
color14 #54ced6
color15 #ffffff
